version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-server
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=127.0.0.1
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=test@123
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=test
      - NACOS_AUTH_IDENTITY_VALUE=test123789
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg5
      - NACOS_AUTH_CACHE_ENABLE=true
    volumes:
      - ./nacos-logs/:/home/nacos/logs
    ports:
        - "8080:8080"
        - "8848:8848"
        - "9848:9848"
    restart: unless-stopped
